### ISSUE TITLE
Rasterstats 0.15.0 is not available on conda-forge

### ISSUE THREAD

**Issue by AndreaGiardini** [conda-forge/rasterstats-feedstock#17]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Rasterstats version 0.15.0 hasn't been published to conda-forge. The latest available version is 0.14.0
https://anaconda.org/conda-forge/rasterstats

Let me know if I can help in any way

**Comment by ocefpaf** [comment]
The PR that added it was merged in https://github.com/conda-forge/rasterstats-feedstock/pull/16

Maybe the CIs failed on master. Investigating...

**Comment by ocefpaf** [comment]
Yep. That was it. I restarted it in #19. The package is in the channel now: https://anaconda.org/conda-forge/rasterstats/files?version=0.15.0

It should take ~1 hour for the CDN to sync and it will be available for installation.

**Comment by AndreaGiardini** [comment]
Thank you @ocefpaf
